### ISSUE TITLE
[Feature] Export type specimen to PDF

### ISSUE THREAD

**Issue by jess-lowe** [typefaceoff/typefaceoff#67]
### Feature Description

Allow the type specimen to be exported to pdf

### Reason for Change

This will allow users to have a digital copy of the type specimen to store beyond the initial session. 

### Where are the changes needed?

An export component would likely need to be created.

**Comment by rhun558** [comment]
Picked up the issue
Found 2 resources that can be installed in order to export to pdf, jspdf (https://udithajanadara.medium.com/export-react-component-as-a-pdf-5afba8ba02ee) and React-PDF (https://react-pdf.org/)
Attempted to install jspdf with npm install jspdf --save
Got this error: 
![image](https://github.com/typefaceoff/typefaceoff/assets/100541562/78d2ceb0-a2cf-4478-8ebb-c98187ac521c)
Tried to update eslint.
Got this error: 
![image](https://github.com/typefaceoff/typefaceoff/assets/100541562/50afa23a-af4a-4389-b5cc-4c6638b0490b)
and 
![image](https://github.com/typefaceoff/typefaceoff/assets/100541562/5d4e793a-2e05-4d4c-8f7a-9336635c9914)
Attempted to update swc, core, ts-node, node, react. Nothing worked, all had the same error with eslint as well.
Tried to install react-pdf instead. Got this: 
![image](https://github.com/typefaceoff/typefaceoff/assets/100541562/45fb15e7-cfdd-48db-ac2a-e41968847b06)

I think since I can't seem to figure this out, passing it to someone else may be the best use of time.
Good luck 😭

**Comment by jaskfla** [comment]
Just throwing in my two cents (it wouldn’t be in the spirit of the assignment for me to actually work on this), but have you considered just using the browser’s built-in print function? If you decide that’s appropriate, `@media print` and the [`@page` model](https://www.smashingmagazine.com/2015/01/designing-for-print-with-css/) would be relevant.

**Comment by calebWei** [comment]
> Picked up the issue Found 2 resources that can be installed in order to export to pdf, jspdf (https://udithajanadara.medium.com/export-react-component-as-a-pdf-5afba8ba02ee) and React-PDF (https://react-pdf.org/) Attempted to install jspdf with npm install jspdf --save Got this error: ![image](https://user-images.githubusercontent.com/100541562/269817707-78d2ceb0-a2cf-4478-8ebb-c98187ac521c.png) Tried to update eslint. Got this error: ![image](https://user-images.githubusercontent.com/100541562/269817904-50afa23a-af4a-4389-b5cc-4c6638b0490b.png) and ![image](https://user-images.githubusercontent.com/100541562/269817954-5d4e793a-2e05-4d4c-8f7a-9336635c9914.png) Attempted to update swc, core, ts-node, node, react. Nothing worked, all had the same error with eslint as well. Tried to install react-pdf instead. Got this: ![image](https://user-images.githubusercontent.com/100541562/269818240-45fb15e7-cfdd-48db-ac2a-e41968847b06.png)
> 
> I think since I can't seem to figure this out, passing it to someone else may be the best use of time. Good luck 😭

running npm update before installing jspdf has worked for me
